server {
    listen 80;

    # 1. Servir el Frontend
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Redirigir las llamadas a la API
    location /api/ {
        # 'backend' es el nombre del servicio en el compose
        # El puerto 8080 es el que usa tu API internamente
        proxy_pass http://backend:8080; 
        #proxy_pass http://host.docker.internal:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}