spring.application.name=JapoApp
# Spring buscará la variable de entorno y si no existe usará '*'
CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:*}
# Debe estar así para que Nginx lo encuentre desde fuera del contenedor
server.address=0.0.0.0
server.port=8080