name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'   # <-- Añade esta línea
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package -DskipTests
      working-directory: SakuraJi-Api


    - name: Copy jar to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "SakuraJi-Api/target/JapoApp-0.0.1-SNAPSHOT.jar"
        target: "/home/ubuntu/"

    - name: Restart Spring Boot app on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pkill -f 'java -jar' || true
           java -jar /home/ubuntu/SakuraJi-Api/target/JapoApp-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
